# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
sudo: false
cache: packages
warning_are_errors: true

os:
  - linux
  - osx

r: 
  - oldrel
  - 3.6
  - release
  - devel
  
after_success:
  - Rscript -e 'covr::codecov(type="all")'
