### Z test for Arcs FOR UNIFORM DISTRIBUTION:
# Ho=L~Bin(g(g-1), 1/2)
# if p > 0.001, 0.05 or 0.1 then 
# one would conclude that the choices of the `G` network
# have been generated by a Bernoulli process
# with p=1/2
# else p < 0.001, 0.05 or 0.1 then
# is unlikely that these data could have
# been generated by a Bernoulli process
zarc <- function(G){
  G <- as.matrix(G)
  G <- ifelse(G>0, 1, 0) # assumed dichotomic!
  l <- sum(G)
  g <- dim(G)[1]
  z <- ((l - ((g*(g-1))/2)))/(sqrt((g*(g-1))/4))
  p <- 2*pnorm(-abs(z))
  res = c(z = z,p = p)
  res
}
zarc(SC)

# GENERALIZED FOR BERNOULLI MODELS:
# default= Uniform distribution
ZBarc <- function(G, p=0.5){
  G <- as.matrix(G)
  G <- ifelse(G>0, 1, 0) # assumed dichotomic!
  l <- sum(G)
  g <- dim(G)[1]
  q = 1-p
  z <- ((l - ((g*(g-1))*p)))/(sqrt((g*(g-1))*p*q))
  p <- 2*pnorm(-abs(z))
  res = c(z = z,p = p)
  res
}
# Lets suppose that the probabilities of ties is 1/4:
ZBarc(SC, p=1/4)
# We would reject the null hypothesis here, 
# and conclude that there is NO evidence that a Bernoulli 
# process with an arc probability of 1/4 
# could have generated the network `G` choices made by 
# these actors.

# UNKNOWN PROBABILITY (p. 534 W-F)
# IT THIS GRAPH A BERNOULLI DISTRIBUTION?
zIntervals <- function(G){
  G <- as.matrix(G)
  G <- ifelse(G>0, 1, 0) # assumed dichotomic!
  l <- sum(G)
  g <- dim(G)[1]
  p_maxlike <- l/(g*(g-1))
  p_lower <- p_maxlike-1.96*(sqrt((p_maxlike*(1-p_maxlike))/(g*(g-1))))
  p_upper <- p_maxlike+1.96*(sqrt((p_maxlike*(1-p_maxlike))/(g*(g-1))))
  res = c(p_maxlike = p_maxlike, p_lower = p_lower, p_upper=p_upper)
  res
}
zIntervals(SC)